services:
  - type: web
    name: spring-api
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/searcher-0.0.1-SNAPSHOT.jar
    repo: https://github.com/heartchangeof8/searcher
